import Foundation

// Stable identifier used for both the macOS LaunchAgent label and Nix-managed defaults suite.
// nix-luckynemo writes app defaults into this suite to survive app bundle identifier churn.
let launchdLabel = "ai.luckynemo.mac"
let gatewayLaunchdLabel = "ai.luckynemo.gateway"
let nodeLaunchdLabel = "ai.luckynemo.node"
let onboardingVersionKey = "luckynemo.onboardingVersion"
let onboardingSeenKey = "luckynemo.onboardingSeen"
let onboardingSystemAgentPendingKey = "luckynemo.onboardingSystemAgentPending"
// Pre-rename releases persisted pending activations under the Crestodian key.
let onboardingSystemAgentPendingRetiredKey = "luckynemo.onboardingCrestodianPending"
let currentOnboardingVersion = 8
let pauseDefaultsKey = "luckynemo.pauseEnabled"
let iconAnimationsEnabledKey = "luckynemo.iconAnimationsEnabled"
let swabbleEnabledKey = "luckynemo.swabbleEnabled"
let swabbleTriggersKey = "luckynemo.swabbleTriggers"
let voiceWakeTriggerChimeKey = "luckynemo.voiceWakeTriggerChime"
let voiceWakeSendChimeKey = "luckynemo.voiceWakeSendChime"
let showDockIconKey = "luckynemo.showDockIcon"
let defaultVoiceWakeTriggers = ["luckynemo"]
let voiceWakeMaxWords = 32
let voiceWakeMaxWordLength = 64
let voiceWakeMicKey = "luckynemo.voiceWakeMicID"
let voiceWakeMicNameKey = "luckynemo.voiceWakeMicName"
let voiceWakeLocaleKey = "luckynemo.voiceWakeLocaleID"
let voiceWakeAdditionalLocalesKey = "luckynemo.voiceWakeAdditionalLocaleIDs"
let voicePushToTalkEnabledKey = "luckynemo.voicePushToTalkEnabled"
let voiceWakeTriggersTalkModeKey = "luckynemo.voiceWakeTriggersTalkMode"
let talkEnabledKey = "luckynemo.talkEnabled"
let talkPhaseSoundsEnabledKey = "luckynemo.talkPhaseSoundsEnabled"
let talkShiftToStopEnabledKey = "luckynemo.talkShiftToStopEnabled"
let iconOverrideKey = "luckynemo.iconOverride"
let connectionModeKey = "luckynemo.connectionMode"
let remoteTargetKey = "luckynemo.remoteTarget"
let remoteIdentityKey = "luckynemo.remoteIdentity"
let remoteProjectRootKey = "luckynemo.remoteProjectRoot"
let remoteCliPathKey = "luckynemo.remoteCliPath"
let canvasEnabledKey = "luckynemo.canvasEnabled"
let quickChatEnabledKey = "luckynemo.quickChatEnabled"
let cameraEnabledKey = "luckynemo.cameraEnabled"
let computerControlEnabledKey = "luckynemo.computerControlEnabled"
let locationModeKey = "luckynemo.locationMode"
let locationPreciseKey = "luckynemo.locationPreciseEnabled"
let peekabooBridgeEnabledKey = "luckynemo.peekabooBridgeEnabled"
let deepLinkKeyKey = "luckynemo.deepLinkKey"
let cliInstallPromptedVersionKey = "luckynemo.cliInstallPromptedVersion"
let cliInstallPolicyKey = "luckynemo.cliInstallPolicy"
let cliManagedRestartPendingKey = "luckynemo.cliManagedRestartPending"
let postAppUpdateReceiptKey = "luckynemo.postAppUpdateReceipt"
let lastLaunchedAppVersionKey = "luckynemo.lastLaunchedAppVersion"
let cliValidatedExecutableKey = "luckynemo.cliValidatedExecutable"
let cliValidatedVersionKey = "luckynemo.cliValidatedVersion"
let macNodeIdentityProfileKey = "luckynemo.macNodeIdentityProfile"
let heartbeatsEnabledKey = "luckynemo.heartbeatsEnabled"
let debugPaneEnabledKey = "luckynemo.debugPaneEnabled"
let debugFileLogEnabledKey = "luckynemo.debug.fileLogEnabled"
let appLogLevelKey = "luckynemo.debug.appLogLevel"
let voiceWakeSupported: Bool = ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26
