<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>x64;ARM64</Platforms>
    <RootNamespace>LuckyNemo.Chat</RootNamespace>
    <AssemblyName>LuckyNemo.Chat</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LuckyNemo.Shared\LuckyNemo.Shared.csproj" />
  </ItemGroup>

</Project>
